### ISSUE TITLE
Make Nammu's console resizable

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/nammu#125]
I think I saw Eleanor trying to resize it, but it is not possible at the moment. I think it's easy enough to just get it done now.

**Comment by raquel-ucl** [comment]
Done in #126.

**Comment by jenshnielsen** [comment]
Normally I would close the issue when the PR is merged?

**Comment by raquel-ucl** [comment]
Sure, I didn't mean to close it yet.

**Comment by jenshnielsen** [comment]
Just testing the PR locally. Will merge if it works as expected

**Comment by raquel-ucl** [comment]
Sure! There's other way to do the resizing: fixing the size of the text area and resizing vertically the whole window. I chose to keep the main window fixed instead, but let me know if you think it'd be better otherwise.

**Comment by jenshnielsen** [comment]
I think this is nice. Perhaps it would be useful with a button that toggles the visibility of the console?

**Comment by raquel-ucl** [comment]
Oh yeah, that'd be nice. I'll make an issue, but as low priority for now.
