### ISSUE TITLE
Tool tips don't disappear after correction and lemmatisation

### ISSUE THREAD

**Issue by jenshnielsen** [oracc/nammu#149]
As demonstrated in the seminar today.

**Comment by jenshnielsen** [comment]
Probably don't clear on lemmatise?

**Comment by raquel-ucl** [comment]
This was fixed in #116 
The problem was the clearing functionality for tooltips didn't work properly, so I overrode getToolTipText so that it returns None when mouse position is in a line without validation errors. This disables the tooltip.
