### ISSUE TITLE
What to do with functionalities like settings, print and model view?

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/nammu#152]
They are not properly functional yet. Should we remove them for the next release?

**Comment by EleanorRobson** [comment]
Leave them in, I think: it's helpful to show people that they are planned.

**Comment by raquel-ucl** [comment]
OK, maybe what I can do is change the icons' colour to grey so it looks disabled.

**Comment by EleanorRobson** [comment]
Yes, good plan -- thanks!

**Comment by raquel-ucl** [comment]
Changed and now the toolbar looks like this:

![screen shot 2016-06-28 at 12 09 56](https://cloud.githubusercontent.com/assets/10402246/16413353/56b51ffe-3d29-11e6-96a4-f3ae945e95dc.png)

I should probably also create a pop up window that says "Coming soon" for print file and edit settings. For the model view, I'm not sure if I should disable completely so the window doesn't prompt, or add a text at the top saying it's under contruction. What do you think is best, @EleanorRobson?

**Comment by EleanorRobson** [comment]
That looks good! Yes, a notice to say that Model View is under construction would be most helpful.

**Comment by raquel-ucl** [comment]
Changed that. This is how it looks now:

<img width="842" alt="screen shot 2016-06-28 at 15 00 07" src="https://cloud.githubusercontent.com/assets/10402246/16418294/0ef8c216-3d41-11e6-8ce4-68d9fe40366e.png">

I also observed if the file is not valid, the model view won't open, but it won't show a message either. I've made it now so that it displays a PyOracc warning pointing to the validation error in Nammu's console, for example, for a text that has and &-line like this:

```
& =
```

This will be shown in Nammu's console: 

```
PyOracc could not parse token 'LexToken(EQUALS,u'=',1,2)'
```

Does this look alright?

**Comment by EleanorRobson** [comment]
Thanks! Model View's mostly going to be used by people who find ATF a bit scary, so that error message will be utterly incomprehensible, I'm afraid. Is it possible to add something more human-readable to it? (e.g., "Please correct the text ID and/or designation.")

**Comment by raquel-ucl** [comment]
I think PyORACC is not ready to do that yet. The best thing we could do without extra work on PyORACC is to format the message to say `the error is word XXXX, line N, position X`. The other option is force server validation before displaying the model view, but if the user is offline it won't be of much help.

**Comment by EleanorRobson** [comment]
Yes, that sounds very sensible :)

**Comment by raquel-ucl** [comment]
Do you mean the error message pointing user to line N, position X, or the server validation?

**Comment by EleanorRobson** [comment]
Ah sorry, I meant the error message pointing to the line & position. (Am in the middle of writing feedback on essays, castigating students for not being clear enough about what they mean! I should follow my own advice...)

**Comment by raquel-ucl** [comment]
@jenshnielsen I'm trying to deal with the SyntaxError exception raised by pyoracc, which apparently has this fields:

```
'args', 'filename', 'lineno', 'message', 'msg', 'offset', 'print_file_and_line', 'text'
```

I was going to use `lineno` and `offset` to build the error message, but they are `None`. Apparently all the attributes are `None` except for `msg` and `message` which contain the whole error message. I was wondering if there is something we can change in PyOracc to populate these fields or if it's a error in Ply or I'm looking at the wrong place. You know more about this than me :)

**Comment by raquel-ucl** [comment]
Made some fixes in PyORACC to pass that information on so Nammu can print user friendly messages pointing to line and character position. Changes are under review [here](https://github.com/oracc/pyoracc/pull/65). I'll change Nammu once that's merged.

**Comment by raquel-ucl** [comment]
Done. Now if there is an error when trying to display the model view, the user will see:

```
There is a syntax error near character '=' in line 1 and position 2.
```

**Comment by EleanorRobson** [comment]
Excellent, thank you!
