### ISSUE TITLE
Indented transliteration lines erroneously repeated after lemmatisation

### ISSUE THREAD

**Issue by EleanorRobson** [oracc/nammu#158]
It's valid ATF to split a long transliteration line with a hard return, like this:

31.	UMUŠ ana {lu₂}UN-MEŠ šu₂-nu-tu₂ iq-bi um-ma {d}na-na-a-a ana BAR.SIP₃{ki} ana E₂.ZI.DA
        i-te-ru-ub ha-an-ṭiš {lu₂}DUMU RI#.ZA₃# šu₁₀-[a-ti₃]

When I run the lemmatiser in Nammu it correctly lemmatises both parts of the line but then wrongly repeats the second half of the line *under* the lemmatisation, like this:

31.	UMUŠ ana {lu₂}UN-MEŠ šu₂-nu-tu₂ iq-bi um-ma {d}na-na-a-a ana BAR.SIP₃{ki} ana E₂.ZI.DA 
     i-te-ru-ub ha-an-ṭiš {lu₂}DUMU RI#.ZA₃# šu₁₀-[a-ti₃]
#lem: ṭēm[mind]N; ana[to]PRP; X; šunūtu[those]IP; iqbi[speak]V; umma[saying]PRP; X; ana[to]PRP; X; ana[to]PRP; Ezida[1]TN; X; hanṭiš[quickly]AV; mār[son]N; X; X

 	**i-te-ru-ub ha-an-ṭiš {lu₂}DUMU RI#.ZA₃# šu₁₀-[a-ti₃]**

And the checker correctly flags that as an error. This needs to be fixed at some point, clearly, but if it's difficult, for now I can just tell editors not to do this :)

**Comment by raquel-ucl** [comment]
I have reproduced your error and double checked now. During the lemmatisation process, Nammu sends the contents of the text area to the server, and when the lemmatisation is ready, it replaces the contents of the area with the __autolem__ file created in the server, as it is returned. Nammu doesn't modify the text returned from the server at all. If there are repeated lines that shouldn't be there, they are coming from the server. 

Are you seeing this behaviour in Emacs as well?

**Comment by EleanorRobson** [comment]
Ah sorry, yes — it is a server-side error. Ignore this and I'll move it to the other bug-report list. I'll also make sure to double-check against Emacs in future so as not to waste your time :)

**Comment by raquel-ucl** [comment]
No problem! It was very quick to check :) Hope the problem is easy to fix.
