### ISSUE TITLE
Update needed for Readme.md

### ISSUE THREAD

**Issue by EleanorRobson** [oracc/nammu#173]
Raquel, if you get a chance today, could you update the links in https://github.com/oracc/nammu/blob/master/README.md to point to the current release of Nammu? At the moment there's a mix of v0.1 and v0.1.1. I don't want any of our users to accidentally use the earlier versions. Thanks!

**Comment by raquel-ucl** [comment]
Done in #174 

I have also added some info as per @jenshnielsen 's suggestion to guide users when reporting issues. See [here](https://github.com/oracc/nammu/issues/new).

Does this look OK to you @EleanorRobson ?
