### ISSUE TITLE
Syntax colouring slow to update in split screen

### ISSUE THREAD

**Issue by EleanorRobson** [oracc/nammu#184]
In Nammu 0.4, when I edit in split-screen mode the syntax highlighting in the active pane is very slow. You'll see in the attached screenshot that new text inherits the colour of the first character of the line(s). It seems to update only when I move out of Nammu into another application (e.g., Firefox, to look at an online image of the object I'm editing) and back again. 
![colourisation](https://cloud.githubusercontent.com/assets/4301009/18245052/045bfa1c-735b-11e6-8617-fdfc4c06887a.jpg)
Non-urgent for me but may be confusing for other users.

**Comment by raquel-ucl** [comment]
I've just had a look in the code.

At the moment the top area in this type of split and the left area in the horizontal one are considered the main edit areas. The secondary areas inherit the styling from the the main ones, so they are supposed to be synchronised. However, syntax highlighting is another story, and it is being only applied in the main edit areas on key released. There is not a quick way to update the syntax highlight in the secondary areas.

We can make the bottom panel the main area in horizontal split, it's possibly the most natural way for it to work, but I didn't realise at the time I made the release. However there might be users that edit in both screens and it's better we make syntax highlighting work in both panels so people can edit in any of them.

We can refactor the SyntaxHighlighter class to update both panels, or else find a way to make a listener for the secondary panels to detect syntax highlighting happening in the main ones and apply syntax highlighting in the secondary ones. 

I think any of these is going to make things super slow for large files, so we'd need to study SpringWorkers and other methods to make highlight less heavy than it is now.

PS - That's a scary text!

**Comment by EleanorRobson** [comment]
In fact one's normally editing in both panels at once: adding the lemmatisation in one panel, and the matching translation in the other. But, as I say, it's non-urgent so don't add this to your September list — I'd rather have search-and-replace working first :)

**Comment by raquel-ucl** [comment]
Sure, I'll focus on search + replace for next release.

**Comment by raquel-ucl** [comment]
I think it's fixed in #188 with a very small change. It doesn't matter now which panel is used as main or secondary in split view, they should both have syntax highlighting working properly.

**Comment by EleanorRobson** [comment]
Fantastic news, and perfect timing, as I'm off to Berlin this evening for a workshop called "Towards a Digital Infrastructure for the study of Historical Languages" where I'll be presenting on Oracc tomorrow afternoon :)

**Comment by raquel-ucl** [comment]
Oh, then I'll prepare a new release with this change so you can test it today and see if you can use it tomorrow.

**Comment by EleanorRobson** [comment]
That would be excellent, thanks so much!

**Comment by raquel-ucl** [comment]
0.4.1 release in JAR and DMG ready for you to test [here](https://github.com/oracc/nammu/releases/tag/v0.4.1). 

Please let me know if you find any problems and I'll try to fix them before the demo.

**Comment by EleanorRobson** [comment]
Got it, thanks so much! I'll let you know how it goes :)

**Comment by EleanorRobson** [comment]
Yes, happy to say that I can now edit very easily the same file that was causing me problems before. It's an incantation to cure illness, BTW — and I hope it works, as I don't feel great today! :)

**Comment by raquel-ucl** [comment]
Glad to hear it's fixed now. Hope you feel better soon!
