### ISSUE TITLE
Logging system

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/nammu#20]
Nammu needs a logging system that'll be displayed in the console. Any useful libraries for this in python or just use log4j?

**Comment by raquel-ucl** [comment]
Basic logging functionality added - just print outs in the console panel by now.

**Comment by raquel-ucl** [comment]
More sophisticated loggins system is still needed.

**Comment by raquel-ucl** [comment]
Eleanor wants the log to be saved in a local file and the list and number of errors/warnings to appear in the log as well.

**Comment by jamespjh** [comment]
The python logging library https://docs.python.org/2/howto/logging.html#logging-basic-tutorial is very mature and good. But so is log4j. :-)

**Comment by raquel-ucl** [comment]
I'll use the python's logging module. See progress on #95.

**Comment by raquel-ucl** [comment]
Some notes on this:

- Use [`RotatingFileHandler`](https://docs.python.org/2/library/logging.handlers.html#rotatingfilehandler) instead of [`FileHandler`](https://docs.python.org/2/library/logging.handlers.html#filehandler) to avoid filling up user's disk with Nammu's log.
- There's an [`SMTPHandler`](https://docs.python.org/2/library/logging.handlers.html#smtphandler) to send certain log messages to email address. Maybe we can configure an oracc dev email account and have the messages sent there.
- File handlers should point to `%appdata%` in windows machines and `/var/log` in the Mac/Linux. Check if those exist when starting Nammu and if they don't, prompt user to choose log file path.

**Comment by jamespjh** [comment]
/var/log/nammu not toplevel /var/log

**Comment by jamespjh** [comment]
If you want to be really sophisticated, you can pick up a logging location from a .nammurc if present, then /etc/nammu on mac and linux, and registry on windows.

**Comment by jamespjh** [comment]
I've done this code a few times, with yaml config file cascades.

**Comment by raquel-ucl** [comment]
@jamespjh do you have that code somewhere I can have a look at? That'd be really helpful.

**Comment by raquel-ucl** [comment]
Update:

Logging system is mostly in place. Logging is being shown in the command console as well as being saved in a local file in the home directory and displayed in NAmmu's console for users (only the INFO messages, not to clutter it with DEBUG stuff). 

The initial intent was to save a log file in `/var/log/` in Unix machines and in `%APPDATA%` in Windows machines, but the application has no permissions, so log is being saved in `~.nammu/`. It's configured so that when it's 50MB, it writes in a new file, and when the second file reaches 50MB it overwrites the oldest part of the older file.

Configuration of log files done in YAML didn't work, but needs to be revisited. Last version using the yaml configuration is ab5b830. PyYAML was installed with maven-jython-plugin correctly since it seemed to work in the output jar file, but the it wasn't found in the build test stage. I couldn't figure out what the problem was and since it was taking too long and wanted to make progress, I reverted back to not using YAML and went on with progress. I will try it again now while I do some refactoring of `NammuController` and `SOAPClient`.

**Comment by raquel-ucl** [comment]
YAML configuration of logging works now, and some refactoring done to avoid duplication in `SOAPClient` and `NammuController`.
Awaiting code review comments.
