### ISSUE TITLE
In Nammu 0.5.5 the New ATF dialogue doesn't accept non-ASCII characters

### ISSUE THREAD

**Issue by EleanorRobson** [oracc/nammu#213]
The New ATF dialogue box doesn't accept non-ASCII characters, as I discovered when typing an en-dash (–) into the "=" (designation) box. The "create template" button then didn't work.

However, all Unicode characters should be allowed here, as some tablet designations include characters such as Š.

**Comment by raquel-ucl** [comment]
I hadn't thought about that! Just solved in #214. It'll be fixed in the next release.

**Comment by raquel-ucl** [comment]
@EleanorRobson the new version with this problem fixed as well as the languages change we did together on Wednesday is here: https://github.com/oracc/nammu/releases/download/0.5.0/nammu-0.5.6.jar

**Comment by EleanorRobson** [comment]
Yes, all ok now — thanks so much!
