### ISSUE TITLE
Document how to add the TextLineNumber class in a development environment

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/nammu#231]
At the moment, Nammu can be run locally because the TextLineNumber class that we use since #113 is in the current folder when loading the python console. That is a bit messy. The class files are already [in the repo](https://github.com/oracc/nammu/tree/master/resources/lib). We just need to add in the [wiki's documentation](https://github.com/oracc/nammu/wiki/Running-Nammu-from-a-console) that developers need to set their env var `$CLASSPATH` to point to that folder.

In the long term it'd be a good idea to investigate how to build the class file from [the java file](https://github.com/oracc/nammu/tree/master/resources/external) during the maven build stage, then use the `copy-resources` maven plugin to put the class file on the right place.

UPDATE:

When we add a `$CLASSPATH` in the environment we are unable to run nammu as we get the following error:

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "python/nammu/controller/NammuController.py", line 73, in __init__
    self.logger = self.setup_logger()
  File "python/nammu/controller/NammuController.py", line 801, in setup_logger
    yaml_dict = get_yaml_config('logging.yaml')
  File "python/nammu/utils/__init__.py", line 124, in get_yaml_config
    path_to_jar = str(config_file_url).split('file:')[1]
IndexError: index out of range: 1
```

To solve this the user needs to set the `$JYTHONPATH` environment variable rather than the `$CLASSPATH` variable to point to the class files [in the repo](https://github.com/oracc/nammu/tree/master/resources/lib)

**Comment by sgrieve** [comment]
Closed. See #271 for details.
