### ISSUE TITLE
Saving new files in working directory

### ISSUE THREAD

**Issue by EleanorRobson** [oracc/nammu#232]
Once the working directory has been set in Nammu's settings, it would make sense for new files to be saved there by default. But now, when you save a new atf file, the dialogue box opens at the Desktop instead of the working directory.

**Comment by raquel-ucl** [comment]
@EleanorRobson you're right, behaviour should be as you say. We have just fixed it now, so it'll work on the next release. Thanks for the report!

**Comment by EleanorRobson** [comment]
And thanks for fixing it! (Hello and thank you too, @sgrieve :) )

**Comment by raquel-ucl** [comment]
No problem! I'll introduce you two in a couple days :)

**Comment by sgrieve** [comment]
Hi @EleanorRobson, looking forward to meeting you on Wednesday 👍
