### ISSUE TITLE
Refactor SyntaxHighlighter to use the new compiled regex method

### ISSUE THREAD

**Issue by sgrieve** [oracc/nammu#239]
As part of #234 we have implemented a new method to translate a line number into a caret position. This method makes use of a compiled regex expression. This same logic is used in `SyntaxHighlighter.py` and we can get a free optimisation of the syntax highlighting by using the new method instead of the old code.

**Comment by raquel-ucl** [comment]
Yes please! 

The whole of the Syntax Highlighter can do with some refactoring. 

And testing.

Low priority, though.
