### ISSUE TITLE
files not being saved to default directory

### ISSUE THREAD

**Issue by zarpanitu** [oracc/nammu#249]
I've changed my default working directory via the settings, but my .atf files are still not getting saved there. I'm using 0.6.0.

**Comment by sgrieve** [comment]
Hi @zarpanitu this is an issue that has been resolved in our [newest release](https://github.com/oracc/nammu/releases/tag/0.7.0) Please let us know if you find any other problems with the new version.

**Comment by zarpanitu** [comment]
OK, thanks - I couldn't access the newest release, but I have it now..
