### ISSUE TITLE
typeface is too small

### ISSUE THREAD

**Issue by zarpanitu** [oracc/nammu#250]
l can't read the text in the console, the ability to increase the font size would improve accessibility.

**Comment by sgrieve** [comment]
Hi @zarpanitu, thanks for the suggestion. This is something we are currently working on and hope to have a new version released soon to address these issues. In the first instance we intend to make the console look more like the emacs console and also to allow the user to set the font size in the settings file and the settings menu.

Are there any other related changes you could suggest to further enhance accessibility?

**Comment by zarpanitu** [comment]
Thanks, that's great news! Otherwise I really like the console (can't remember what the emacs one looks like, it's many years since I used emacs). I can't think of anything else at the moment.

**Comment by sgrieve** [comment]
Great! When we have a prototype of the improved console I will notify you to get some feedback.

**Comment by sgrieve** [comment]
We have implemented this feature, which will appear in the next release of Nammu, alongside other interface enhancements which are out of the scope of this issue.
