### ISSUE TITLE
Cursor jumps to the end of the file after lemmatisation

### ISSUE THREAD

**Issue by EleanorRobson** [oracc/nammu#259]
It would be really helpful if nammu could remember the position of the cursor before lemmatisation, and return it there afterwards.

**Comment by sgrieve** [comment]
Hi @EleanorRobson,

Thanks for this, I will take a look and try and get this fixed for the next release.

**Comment by sgrieve** [comment]
This is resolved as part of #262 and will be closed when it is merged.
