### ISSUE TITLE
Interface does not respond in Linux with multiple versions of Java

### ISSUE THREAD

**Issue by willismonroe** [oracc/nammu#260]
I'm having trouble using the interface, buttons and menus do not seem to respond to mouse clicks or keyboard keyboard input.  Menus will open even when the pointer is over the main edit box and the button clicked, but none of the menu options will then register a mouse click (for example).

Platform: Linux (Ubuntu 17.04)
Nammu versions: 0.7.1, 0.6.0, 0.3.0
Java versions: OpenJDK 8, 9, Oracle Java 8

**Comment by raquel-ucl** [comment]
Hi @willismonroe, thanks for the report and sending your system details.

We're going to try to reproduce your error and see what could be going wrong. Are you by any chance using a windows manager that could be interfering or adding an offset to your mouse position? If you could let us know what window manager you're using, that would be really appreciated.

**Comment by willismonroe** [comment]
Hi Raquel,

Thanks for checking.  Your intuition was correct.  I am running a 4k display set to 1920x1080 resolution, at that resolution the interface does not function correctly.  When I returned to the native resolution I was able to use the interface both in 1x1 scale as well as 1x2 scale.  Seems like it might be a bug in AWT?  But nevertheless it works for me now.

**Comment by raquel-ucl** [comment]
Happy to hear it works for you now!  Can I close the issue?

**Comment by willismonroe** [comment]
Yep, thanks.
