### ISSUE TITLE
saving allows other extensions than .atf

### ISSUE THREAD

**Issue by niekveldhuis** [oracc/nammu#278]
Nammu 0.8.0
Mac OS X
When creating a new file, when you first try to validate, Nammu wants you to first save the file.  In saving, it allows any file extension. Once saved with, say a .txt extension (or no extension at all) Validate seems to work fine, but always returns "The validation returned no errors". It does not give a warning about the file extension.

Niek

**Comment by sgrieve** [comment]
Hi @niekveldhuis, thanks for this bug report.

To resolve this issue I have made two changes:

1. Nammu will now not attempt to send a non `*.atf` file to the server for validation, and will instead warn the user with an error message that they need to change the file format of the file they are working on.

2. The save dialogue will now only save `*.atf` files, to reduce the instances of users trying to validate files of the wrong format.

These changes will be integrated into version 1.0 of Nammu which we are hoping to release in the coming days. If you have any other thoughts or suggestions about this or any other feature of Nammu please let me know.

**Comment by sgrieve** [comment]
Issue is resolved in PR #280 and will be closed upon merge.
