### ISSUE TITLE
Nammu is jumpy when using split editing window

### ISSUE THREAD

**Issue by zarpanitu** [oracc/nammu#296]
When working in split editor mode, the editing window is jumpy. E.g., if I edit the translation in the right-hand pane and align the left-hand pane so that I can see the corresponding transliteration, once I start typing on the right then the left-hand screen scrolls down to the translation. This limits the usefulness of the ability to work with a split editor.

I'm using Nammu 1.0, Mac OS 10.13.

**Comment by EleanorRobson** [comment]
Ah yes, you need to click in the transliteration pane, otherwise Nammu doesn't know where you want to be in that pane. Try that, and the problem should go away.

**Comment by raquel-ucl** [comment]
@zarpanitu did you try Eleanor's suggestion? Please, let us know if you are still finding trouble with this.

**Comment by zarpanitu** [comment]
@raquel-ucl Yes, thanks, it's much better, I just had to retrain myself to do as Eleanor suggested

**Comment by raquel-ucl** [comment]
Great! I'll close the issue then. Please feel free to reopen if you have trouble with it. Thanks!
