### ISSUE TITLE
blank lines in composites

### ISSUE THREAD

**Issue by maeveweber** [oracc/nammu#307]
I am entering a composite text (from a book by Ambos Mesopotamische Baurituale, aus dem 1. Jahrtausend v. Chr.).   (I'll email the file when I get an issue id for this) 
Nammu version :1.0.0
java version:  1.7.0_04
platform:  Windows  7 professional 

This is to flag one of two conventions in this text that are giving a Nammu problem. (The second problem will follow as a separate issue log) 
First the composite text line is not itself supplied by the author.  It is indicated with its (canonical) line number only and then followed by the one or more individual source text lines that correspond to this canonical line with their own line numbers. 
I use the "check current atf correctness" button.   Nammu flags the blank composite line as an error.   

There is a syntax error near character ' ' in line 40 and position 1293.

I can imagine a workaround of inserting some dummy characters into the composite line to get around this problem (e.g [x]?) . This seems pretty messy to me.  Is there any workaround that you know of that means I can continue getting this text into Nammu atf 'as-is'. 
May I just check that a blank line is indeed intended to be a Nammu atf error  (not a warning maybe)  so that this convention in all these Ambos texts is incompatible with atf?
This is the only message I get from Nammu from this file - it feels like a very poor return-on-investment for the time taken to set up Nammu  and then to set up this interface.

**Comment by EleanorRobson** [comment]
Thank you for your report. Nammu is not yet designed to edit composite texts, as the majority of Oracc content creators current work on single-manuscript transliterations. You will find instead that Emacs handles composite texts much more effectively. See here for further information: http://oracc.museum.upenn.edu/doc/help/nammuandemacs/index.html
