### ISSUE TITLE
Line numbers with : (colon)

### ISSUE THREAD

**Issue by maeveweber** [oracc/nammu#308]
I am entering a composite text (from a book by Ambos Mesopotamische Baurituale, aus dem 1. Jahrtausend v. Chr.).   (I'll email the file when I get an issue id for this) 
Nammu version :1.0.0
java version:  1.7.0_04
platform:  Windows  7 professional 
I am using the "check current atf  correctness" button

This is to flag the second of two conventions in this text which is giving a Nammu problem.  This  convention is to distinguish the individual lines that contribute to the composite from the composite itself with the use of colon instead of full-stop/period to delimit the line number designation characters. 
e.g. 
1. 
A1,1’: 
B1,15-16'’:  
where A1 and B1 are individual source text lines from different tablets corresponding to line 1 of the canonical text.  There is no tablet for this line 1.   Each semi-colon delimiter generates a single error message - like this

There is a syntax error near character 'A1' in line 41 and position 1302

I could workaround this I suspect by either converting each semi-colon to full-stop/period or by adding a full-stop/period if I want to retain the distinction between a composite line and the individual contributing lines (in a large text like this) . Maybe the Nammu tool also needs to distinguish the two types of line in a composite(!).  To me this is a messy workaround.  Can you suggest any other workarounds for getting this convention for composite texts acceptable to Nammu ? 

Again this is the only message I get from Nammu from this file after I have resolved previous issue #307 - it feels like a very poor return-on-investment for the time taken to set up Nammu  and then to set up this interface.

**Comment by EleanorRobson** [comment]
Thank you for your report. Nammu is not yet designed to edit composite texts, as the majority of Oracc content creators current work on single-manuscript transliterations. You will find instead that Emacs handles composite texts much more effectively. See here for further information: http://oracc.museum.upenn.edu/doc/help/nammuandemacs/index.html
