### ISSUE TITLE
Creating

### ISSUE THREAD

**Issue by matthewrutz** [oracc/nammu#309]
To help us understand and resolve your issue please check that you have provided
as much of the information below as possible:

* Nammu 1.0
* java version "1.8.0_144"
* OSX (10.12.6)
* How do I create a template that includes the options "Language: alphabetic Ugaritic" and "Language: syllabic Hurrian"?

**Comment by EleanorRobson** [comment]
Those options don't yet exist in Nammu 1.0 so for now:

1. In the New ATF Template dialogue box, just choose any available language.

2. Then when the template has been created, manually delete that language code and type in the one you want as your base language: either uga-040 (see http://oracc.museum.upenn.edu/doc/help/languages/ugaritic/index.html) or xhu, i.e., either, 
#atf: lang uga-040
OR
#atf: lang xhu

3. If you want to switch languages mid-text, follow the instructions here: http://oracc.museum.upenn.edu/doc/help/editinginatf/primer/inlinetutorial/index.html#h_languages
