### ISSUE TITLE
Supporting other right to left languages

### ISSUE THREAD

**Issue by sgrieve** [oracc/nammu#315]
In the process of getting arabic translation support working (see #310) we have to search the text for parallel translation lines:

```
@translation parallel ar project
```

At present this is done in part by checking for the Arabic code `ar` and this search is hardcoded into the code. Is there a need to check for any other right to left language codes?

**Comment by EleanorRobson** [comment]
Thanks Stuart!
First, we should note that it's not just parallel translation lines that are relevant here: 

\@translation labeled
\@translation parallel
\@translation unitary

are all valid: see [http://oracc.org/doc/help/editinginatf/translations/index.html]

As for likely languages using RTL scripts:

* ar = Arabic
* fa = Farsi/modern Persian
* ku = Kurdish

Are all we envisage for the foreseeable future.

**Comment by sgrieve** [comment]
Thanks @EleanorRobson, I will add in the other language codes, and change the logic so that unitary and labeled translations are included.

Would you be able to send me example atf files containing arabic labeled and unitary translations, so that I can test everything?

**Comment by sgrieve** [comment]
Never mind, I have found some english examples on the docs that will work for testing at the moment.

**Comment by sgrieve** [comment]
A quick design question for @EleanorRobson:

In cases where we have `@` lines or other atf stuff interleaved with arabic translations, do users expect to see the `@` line left or right justified?

In other words, in this example, which `@reverse` line is preferred?

<img width="733" alt="screen shot 2018-05-04 at 10 58 31" src="https://user-images.githubusercontent.com/10617231/39622836-88a7a286-4f8b-11e8-985c-1d386dbfca29.png">
<img width="743" alt="screen shot 2018-05-04 at 11 01 33" src="https://user-images.githubusercontent.com/10617231/39622837-8a663862-4f8b-11e8-9c8a-4c6860c80e2c.png">

**Comment by EleanorRobson** [comment]
In terms of aesthetics & legibility, either is fine. As to how the oracc processor would handle it, you'd need to ask @stinney

**Comment by sgrieve** [comment]
Excellent. This shouldn't impact the processor, as it deals in the plain text and ignores the styling. We will proceed with right-justifying these lines, as this is the more efficient solution and should help maintain a responsive editor.
