### ISSUE TITLE
config.xml not found or not readable for newly created project

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/nammu#316]
We downloaded the latest version of Nammu and are running the application in Windows 10 (home and pro)

In Oracc, on the Munich server (oracc.ub.uni-muenchen.de), I created the project adsd and the subprojects adart1, adart2, adart3. 

We open Nammu, open the attached file, and run the validate ATF command. We get the the following message: 

The server returned some errors:

00atf/AD-140C.atf:2:X000001: xpd_init: /home/oracc/xml/adsd/adart3/config.xml not found or not readable
ATF processor ox issued 1 warnings and 0 notices
Please, see highlighted areas and correct errors.

Because the config.xml file is not recognised, we are unable to proceed. Advice?

**Comment by EleanorRobson** [comment]
This isn't a Nammu issue. You need to run oracc build on your new projects to create the config files.

**Comment by jnovotny-lmu** [comment]
Dear E., I have run oracc build several times already and the issue persists. This also happens for ribo/nbk2p1 and ribo/nbk2p2, the first of which has been rebuilt numerous (50+ times) since its creation.
