### ISSUE TITLE
Nammu ATF functions do not work with Munich server settings

### ISSUE THREAD

**Issue by jnovotny-lmu** [oracc/nammu#317]
* Nammu's version: 1.0
* Mac OS 10.13.4

**Steps:** 
1. Open Nammu.
2. Open Preferences and set ORACC server location to 'Munich' (see screenshot).
3. Save Preferences.
4. Open an ATF file with a project on the Munich Server. For example, AD-140.atf
5. Go to the ATF tab of Nammu, and select, e.g., Validate.

**Expected Result:**
Nammu should validate the file.
**Actual Result:**
Nammu does no validate the file. (see screenshot)

The results are the same when the Lemmatise option is selected.

I have tried this on two different Macs. Screenshots of the Preference setting, failed validation, and a sample ATF (coverted here to .txt for upload) are attached.
![nammu-preferences](https://user-images.githubusercontent.com/19565350/40098502-0c45c83a-58dc-11e8-8a18-d4291acb1cf4.png)
![nammu-message](https://user-images.githubusercontent.com/19565350/40098506-0f38625a-58dc-11e8-89b9-4f0a51180819.png)
[AD-140C.txt](https://github.com/oracc/nammu/files/2007628/AD-140C.txt)

**Comment by raquel-ucl** [comment]
Hi Jamie,

Thanks for the report. Stuart and I will have a look into this today. It's odd you are not getting any error message! Can you send us a zip file with the contents of your ".nammu" folder too, please? That folder is a hidden folder that should be in your home directory. Please let us know if you need assistance with this and we can have a short skype call later today.

**Comment by jnovotny-lmu** [comment]
Raquel, 

See the attached ZIP file of the requested folder. 

Jamie

Dr. Jamie Novotny
Akademischer Oberrat
Ludwig-Maximilians-Universität München
Historisches Seminar - Abteilung Alte Geschichte 

Postadresse:
Ludwig-Maximilians-Universität München 
Geschwister-Scholl-Platz 1 
D - 80539 München 

Telefon: 0049-89-2180-3789
email: Jamie.Novotny@lmu.de, Jamie.Novotny@lrz.uni-muenchen.de 

Am 2018-05-16 08:29, schrieb Raquel Alegre:

> Hi Jamie, 
> 
> Thanks for the report. Stuart and I will have a look into this today. It's odd you are not getting any error message! Can you send us a zip file with the contents of your ".nammu" folder too, please? That folder is a hidden folder that should be in your home directory. Please let us know if you need assistance with this and we can have a short skype call later today. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1] https://github.com/oracc/nammu/issues/317#issuecomment-389409393
[2]

**Comment by EleanorRobson** [comment]
Parenthetically, you need to set the language code to a particular dialect of Akk:

#atf: lang akk-x-stdbab

See [http://oracc.museum.upenn.edu/doc/help/editinginatf/primer/inlinetutorial/index.html#h_languages](http://oracc.museum.upenn.edu/doc/help/editinginatf/primer/inlinetutorial/index.html#h_languages) for the fact that "akk" alone is not valid in protocol lines.
