### ISSUE TITLE
Nammu 1.1.0.jar won't open on Mac OS 10.11.6

### ISSUE THREAD

**Issue by EleanorRobson** [oracc/nammu#319]
I'm running Java 1.8.0_91. Nammu downloads ok, but when I double-click to open I get the Oracc splash screen and then error message "The Java JAR file "nammu-1.1.0.jar could not be launched." 

Do I need to upgrade my Java to the latest release? I've been ignoring update messages in case a new version broke Nammu 1.0.

**Comment by raquel-ucl** [comment]
Thanks for the report and sorry to hear the last version didn't work, Eleanor. No need to upgrade Java, there must be a different problem. Can you share the contents of `~/.nammu/nammu.log` and `~/.nammu/settings.yaml` with us? That should give us some more information.

**Comment by EleanorRobson** [comment]
/settings.yaml : 

console_style:
  background_color: {default: Gray, user: Gray}
  font_color: {default: Black, user: Black}
  fontsize: {default: 11, user: 13}
edit_area_style:
  fontsize: {default: 14, user: 14}
find_keystrokes: {find_next: VK_G, replace_all: VK_A, replace_one: VK_R}
keystrokes: {closeFile: VK_W, find: VK_F, lemmatise: VK_L, newFile: VK_N, openFile: VK_O,
  redo: VK_Y, saveAsFile: VK_E, saveFile: VK_S, showHelp: VK_H, splitEditorH: VK_PERIOD,
  splitEditorV: VK_SEMICOLON, syntax_highlight_switch: VK_T, undo: VK_Z, validate: VK_D}
languages: {Conventional Akkadian: akk-x-conakk, Early Akkadian: akk-x-earakk, Emesal: sux-x-emesal,
  Hittite: hit, Late Babylonian: akk-x-ltebab, Middle Assyrian: akk-x-midass, Middle Babylonian: akk-x-midbab,
  Middle Babylonian peripheral: akk-x-mbperi, Neo-Assyrian: akk-x-neoass, Neo-Babylonian: akk-x-neobab,
  Old Akkadian: akk-x-oldakk, Old Assyrian: akk-x-oldass, Old Babylonian: akk-x-oldbab,
  Old Babylonian peripheral: akk-x-obperi, Standard Babylonian: akk-x-stdbab, Sumerian: sux
    or sux-x-emegir, Syllabic: sux-x-syllabic, Udgalnun: sux-x-udgalnun, Ur III Akkadian: ua,
  default: Standard Babylonian}
new_user: false
projects:
  cams: [gkab]
  cmawro: null
  dcclt: [ebla, nineveh, obale]
  default: [cams/misc/behistun]
  etcsri: null
  rimanum: null
  rinap: [rinap1, rinap3, rinap4, senn2, sources]
  saao: [saa01, saa02, saa03, saa04, saa05, saa06, saa07, saa08, saa09, saa10, saa11,
    saa12, saa13, saa14, saa15, saa16, saa17, saa18, saa19]
protocols: [math, legacy, lexical, mylines]
servers:
  default: upenn
  munich: {dir: p, port: 8085, url: 'http://oracc.ub.uni-muenchen.de'}
  upenn: {dir: p, port: 8085, url: 'http://build-oracc.museum.upenn.edu'}
version: 0.17
working_dir: {default: /Users/eleanorrobson/Documents/Teaching/Akk reading group}

**Comment by EleanorRobson** [comment]
And nammu.log (with .txt extension added for upload to Github).
[nammu.log.txt](https://github.com/oracc/nammu/files/2154660/nammu.log.txt)

**Comment by raquel-ucl** [comment]
I can't see anything that looks wrong there, so I'll need to run some local tests first. Stuart is on annual leave, but I should have some time tomorrow. I will update you when we know more.

**Comment by raquel-ucl** [comment]
@EleanorRobson we have now created a new JAR and uploaded it to the releases section:

https://github.com/oracc/nammu/releases/download/untagged-8e81d591d83835d819fb/nammu-1.1.0.jar

Can you try again, please? It should work now.

**Comment by sgrieve** [comment]
We have resolved these issues and Eleanor is able to open jars again.
