### ISSUE TITLE
Update Travis tests to run in Java 8, 9 and 10

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/nammu#321]
We need to create some new tests that:

1. Open Nammu
2. Use setText() on the edit area object
3. Capture errors coming from 2. 

Tests should pass when there are no errors captured.

It'd be also interesting to test SyntaxHighlighting and other text edition features are working. This can be done looking into de attributes assigned to the text added in step 2.

Some related info about Java 9 also in #303.

**Comment by sgrieve** [comment]
This has been completed in #337, aside from the java version issues, which are now listed in #336
