### ISSUE TITLE
Test ideas about right to left implementations

### ISSUE THREAD

**Issue by sgrieve** [oracc/nammu#326]
There are some different suggestions on how best to implement right to left text.

1. Use the special unicode characters to tie passages of text to a given text direction. These characters would needed to be added automatically while the user edits text.

2. Each line of translation exists within its own `JTextPane`, which has the component level text direction set, either automatically, or manually by a series of toggles on each line.

3. We have `right to left` and `left to right` buttons that the user clicks to change the text direction so they can interleave both text directions as they like.

**Comment by giordano** [comment]
This should have been implemented in #338 as a new `JTextPane` dedicated to the Arabic translation.
