### ISSUE TITLE
Create tests for Nammu's GUI

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/nammu#34]
I'll need help from @jamespjh probably :)

**Comment by jamespjh** [comment]
Any progress here @raquel-ucl ?

**Comment by raquel-ucl** [comment]
@jamespjh I have one test for the maven install that publishes the jar in the repo. Last week I was trying to find some tool to do BDD tests, something similar to [Calabash for Android](http://calaba.sh), but for desktop GUIs, but I couldn't find any that is freely available. I'm trying [cucumber](https://cucumber.io), which is not specifically for GUIs, but works with python and I think could do the job. If you have any pointers, it'd be great!

**Comment by jamespjh** [comment]
Cucumber is a good choice, because its  wide applicability means familiarity with it will help for other projects. I believe @mdavezac used it for an earlier project, so he may have tips.

J.

**Comment by mdavezac** [comment]
I used [behave](http://pythonhosted.org/behave/) which is a similar BDB framework for python. It's does not  offer GUI specific functionalities as far as I know.

**Comment by raquel-ucl** [comment]
Thanks, @mdavezac. I'll have a look to behave as well.

**Comment by raquel-ucl** [comment]
I couldn't make this work at the time and run out of time to keep trying. I thought it could work to collect click events from the user, but it didn't appear to work like that with Jython. I run out of time when doing this, but I'll get back to it.

**Comment by raquel-ucl** [comment]
Added some tests to check SOAP functionality. Also added a test to validate the whole corpus using Nammu, but so far is skipped. 
More tests on the way.

**Comment by raquel-ucl** [comment]
Finally! Some progress on this 3 years later :)

Stuart and I have put together some dummy tests on Nammu's text area to test Travis' headless mode (see #335). It's gone well and now he'll add a few more in order to test development of Arabic Nammu for Nahrein. Closing!
