### ISSUE TITLE
Undo fails in Arabic pane

### ISSUE THREAD

**Issue by sgrieve** [oracc/nammu#341]
We need to add an undo manager to the Arabic pane and refactor the undo method in ATFAreaController to reflect the multiple undo managers.

It may be easiest to destroy all record of undos upon toggling of the Arabic pane, as I have no idea how to combine the undo histories from two separate files.

The calls to syntax highlight within the undo method should also probably be replaced with `runSwingLater(self.controller.initHighlighting)` so we don't get threading issues, which I think are the source of the exceptions being thrown when we undo on a single editor pane.

**Comment by raquel-ucl** [comment]
Done!
