### ISSUE TITLE
Check if Nammu can empty local settings file

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/nammu#344]
A user seems to have a problem with her settings file being empty (#339). We don't know the cause, but it'd be worth to check if there's anywhere in Nammu's codebase where the settings file is emptied by some error not being handled properly.

The last line in Nammu's log for this user was an edition of the settings, although a very common one that is all over her log, so it might not be the cause. See 
https://github.com/oracc/nammu/files/2311637/nammu.log.

**Comment by raquel-ucl** [comment]
@ageorgou pointed out that we are opening the settings file in `wb` mode, when we just want to read it. This might cause the file becoming empty. We don't really need `wb` mode, so it might be an easy fix.

Still worth checking if there's other error handling section that might cause the settings file to get emptied when it shouldn't.

**Comment by ageorgou** [comment]
Might be related with #347?

**Comment by giordano** [comment]
We recently improved handling of errors of empty settings files (#406), in the process we couldn't find how they can be emptied by Nammu, so I'm closing this issue.
