### ISSUE TITLE
Recurring errors when lemmatizing new texts

### ISSUE THREAD

**Issue by matthewrutz** [oracc/nammu#349]
* Nammu's version: nammu-1.0.1.jar
* Java version: java version "11.0.1"
* Computer Platform: 10.13.6

I open a new atf file in the corpus. The checker indicates that the atf is clean/valid. I run the lemmatizer and receive the following message, but there are NO highlighted areas, and this notice appears with all new files regardless of content:

![github_lemmatization_problem_08-jan-2019](https://user-images.githubusercontent.com/36307792/50849047-dd6aa080-1343-11e9-8ae4-667398907d23.jpeg)

:

The lemmatisation returned some errors:
/home/oracc/pub/aemw/ugarit/bgrm-akk-x-mbperi.ngm:253: (f2) PNMaÅ¡Å¡ana-urama: bad POS; allowed forms are 'u', 'n', or A-Z+ then optional /i or /t 
/home/oracc/pub/aemw/ugarit/bgrm-akk-x-mbperi.ngm:253: (f2) PNMaÅ¡Å¡ana-urama: bad POS; allowed forms are 'u', 'n', or A-Z+ then optional /i or /t 
/home/oracc/pub/aemw/ugarit/bgrm-akk-x-mbperi.ngm:463: (f2) PNMaÅ¡Å¡ana-urama: bad POS; allowed forms are 'u', 'n', or A-Z+ then optional /i or /t 
/home/oracc/pub/aemw/ugarit/bgrm-akk-x-mbperi.ngm:463: (f2) PNMaÅ¡Å¡ana-urama: bad POS; allowed forms are 'u', 'n', or A-Z+ then optional /i or /t 
ATF processor ox issued 4 warnings and 0 notices 
Please, see highlighted areas and correct errors. 

Any idea why this is happening?

Thank you!

**Comment by raquel-ucl** [comment]
Dear @matthewrutz, thanks for your report.

The errors you report are coming from the Oracc server, and Nammu just reports them blindly, so I'll have to double check with @stinney what this error is about.

About the highlighted lines, I just wanted to double check you have scrolled down to lines 253 and 463, and those are not highlighted. If you look in the error messages, they have the line numbers just before the error message itself.

Would it be possible for you to send us the original ATF file? You could add it to a comment here on GitHub, but you'll need to change the filename so its extension is txt instead of atf. Please, let me know if you need any assistance with that.

**Comment by matthewrutz** [comment]
Dear Raquel,

Thank you for your quick and thoughtful response.

I wasn't sure if this was a Nammu or server issue, and if it's the latter, thanks for your patience.

The odd thing about the error message is that in all cases there are no lines 253 and 463 (always those. Here's the end of the text for which I did the screen grab.

![github_post_text_end](https://user-images.githubusercontent.com/36307792/50909606-31d05780-13fa-11e9-8785-47006c1573c7.jpeg)

Attached is the atf file in txt format, as requested. Thank you!

[RSOu_07_25.txt](https://github.com/oracc/nammu/files/2741493/RSOu_07_25.txt)

**Comment by niekveldhuis** [comment]
Dear Matthew and Raquel,

This is a very strange error. I did some testing - there is something wrong
with how this particular project is handled in Nammu.
First, when I test the file in Emacs I get no errors and it lemmatizes fine.
Second, when I open the file (with .atf extension; without the
lemmatization produced in the previous step) in Nammu (I still have 1.0.0)
I can reproduce Matthew's problem by clicking on "lemmatize" in the ATF
menu. However, if I change the project to dcclt there is no problem and the
file lemmatizes without error.
That indicates to me that this is indeed a Nammu problem - a puzzling one
at that.

Niek

Niek Veldhuis
Professor of Assyriology, Department of Near Eastern Studies
Senior Fellow, Berkeley Institute of Data Science
UC Berkeley

**Comment by raquel-ucl** [comment]
Thanks @niekveldhuis, I will have a closer look at this problem on Friday. It is indeed very puzzling.
Thank you for sending the file @matthewrutz. It is very useful for testing on Friday.

**Comment by raquel-ucl** [comment]
@matthewrutz @niekveldhuis I am sorry I didn't find the time to work on this until last week. I have tried to replicate the error, but lemmatisation is working for me without any issues for this file. Is this error still happening to you?

**Comment by raquel-ucl** [comment]
@stinney do you think something might have changed in the served that could have fixed the problem reported above? @ageorgou also tried to reproduce it but can't. The file is correctly lemmatised by the Oracc server with no errors  for both of us in [version 1.0.1 of Nammu](
https://github.com/oracc/nammu/releases/download/1.0.1/nammu-1.0.1.jar).

**Comment by matthewrutz** [comment]
Thanks for the follow up, @raquel-ucl. There were some issues with the server a few weeks ago, but this error message seems to have disappeared around the same time the other problems were resolved.

**Comment by raquel-ucl** [comment]
Errors that fix themselves are my favourite kind of errors. Thanks for the info, @matthewrutz!
