### ISSUE TITLE
Hurrian protocol/inline codes

### ISSUE THREAD

**Issue by matthewrutz** [oracc/nammu#354]
Is there an established protocol code/inline code for the Hurrian language?

Thanks.

**Comment by niekveldhuis** [comment]
Yes, the language code is xhu (see https://iso639-3.sil.org/code/xhu and
the link to Wikipedia there). I don't think we have proper codes for the
various "dialects" of Hurrian at this point. Hurrian has been used by
DCCLT; there is quite a bit of Urartian in the Munich projects - I do not
know if they have also included Hurrian texts.

Niek

Niek Veldhuis
Professor of Assyriology, Department of Near Eastern Studies
Senior Fellow, Berkeley Institute of Data Science
UC Berkeley

**Comment by matthewrutz** [comment]
Thank you!

**Comment by raquel-ucl** [comment]
Ok, I'll change that and include it in the next release by end of February.

If you want to have Hurrian added already to Nammu without having to wait for the next release, I'd be happy to assist! You will need to send me your config file stored in `~/.nammu/settings.yaml` and I will add the new language there so you have it next time you open Nammu and create a new ATF file.

**Comment by raquel-ucl** [comment]
Regarding the other languages, it is all very straight forward to add, I just need a list like the above with atf language code and language name. Let's wait for @niekveldhuis and @EleanorRobson to approve which ones to add then.

**Comment by jnovotny-lmu** [comment]
We use:
xur = Urartian
xur-944 is used to mark Akkadograms in Urartian (but not used as a main language)
xur-946 is used to mark Sumerograms in Urartian (but not used as a main language)
peo = Old Persian
We also have projects with Elamite (elx). Should we also add Elamite dialects? If so, I will ask Alexa Bartelmus about the various dialects needed.
I agree that we should add Aramaic (arc). Should we also add Phoenician (Phn) and other Semitic languages while we are at it?
We have talked with Mark Weedon about adding Luwian text to Oracc so it would be useful to have that. Birgit, who is working on the Urartian, might want to add Lycian at some point. 
These are just the items I can think of at the moment.

**Comment by jnovotny-lmu** [comment]
I believe we will also start using Hurrian when we enter texts from CTU IV later this year.

**Comment by niekveldhuis** [comment]
I think the list should be as complete as possible, but not include (at
least for now) languages not represented in cuneiform. So as long as no one
is doing anything Phoenician I'd leave it out - but all the others
mentioned by Jamie should be in.

For Hurrian (but this is outside of the issue) it would be really useful to
talk about how to represent Hurrian - there are quite a few different
traditions (phoneme inventory, vowel lengthening, etc.) and we should
follow one as much as possible. I guess the Urartian corpus already
provided a standard that Hurrian could be aligned with.
Niek

Niek Veldhuis
Professor of Assyriology, Department of Near Eastern Studies
Senior Fellow, Berkeley Institute of Data Science
UC Berkeley

**Comment by matthewrutz** [comment]
Have decisions been made about the sources that should be used to generate citation forms and guide words for these languages?

I am particularly interested in Hurrian, Hittite, and Luwian.

Thanks again for the codes,

Matthew

**Comment by niekveldhuis** [comment]
I don't think we have any Hittite today. For Hurrian I would talk to Jamie,
because the decisions should be based on whatever was done for Urartian. I
don't think there is any Luwian in ORACC so far.

Niek

Niek Veldhuis
Professor of Assyriology, Department of Near Eastern Studies
Senior Fellow, Berkeley Institute of Data Science
UC Berkeley

**Comment by jnovotny-lmu** [comment]
For Urartian, we followed Salvini, _Corpus dei testi urartei_ V for the citation form and used an English translation of the Italian original for the Guide Word and followed the rules established for Akkadian to try to maintain a level of consistency across languages. So far we have not lemmatised any Hurrian words. I will Birgit Christiansen, who works with Anatolian languages (including Hittite), to suggest a resource we should follow for Hurrian.

**Comment by raquel-ucl** [comment]
Hi @jnovotny-lmu  and @niekveldhuis,

So this is my updated list of languages right now:

```
Conventional Akkadian: akk-x-conakk, 
Early Akkadian: akk-x-earakk, 
Emesal: sux-x-emesal,
Hittite: hit, 
Late Babylonian: akk-x-ltebab, 
Middle Assyrian: akk-x-midass, 
Middle Babylonian: akk-x-midbab,
Middle Babylonian peripheral: akk-x-mbperi, 
Neo-Assyrian: akk-x-neoass, 
Neo-Babylonian: akk-x-neobab,
Old Akkadian: akk-x-oldakk, 
Old Assyrian: akk-x-oldass, 
Old Babylonian: akk-x-oldbab,
Old Babylonian peripheral: akk-x-obperi, 
Standard Babylonian: akk-x-stdbab, 
Sumerian: sux-x-emegir,
Syllabic: sux-x-syllabic, 
Udgalnun: sux-x-udgalnun, 
Ur III Akkadian: akk-x-ur3akk,
Urartian: xur,
Urartian Akkadograms: xur-944,
Urartian Sumerograms: xur-946,
Old Persian: peo,
Hurrian: xhu,
Elamite: elx,
Aramaic: arc
```

I am trying to create a new release with some Arabic edition functionality for Monday and I was wondering if you could review and confirm this list of languages is what you'd expect. Is there anything I'm missing or anything that shouldn't be there?

I'm unclear as to whether I should keep the Urartian Akkadograms and Sumerograms since they are not used as main languages. Can you confirm, please?
Also, does Luwian have an ATF metadata code so I can add it to the list too?

Thanks!

**Comment by jnovotny-lmu** [comment]
@raquel-ucl,
I would delete `Urartian Akkadograms: xur-944` and `Urartian Sumerograms: xur-946` as they will not ever be used as a main language. We also use Aramaic, but at this time (and I assume going forward; see above) it will not be used as a main language so it should not be included. 
I am wondering if we should sub-divide `Elamite: elx`. [@niekveldhuis, thoughts on this?]
Luwian does not yet have an ATF metadata code. In my opinion, we can leave that out for the time. I leave that for Niek to decide.

**Comment by raquel-ucl** [comment]
Thanks for the quick reply @jnovotny-lmu !

So the amended list would be:

```
Conventional Akkadian: akk-x-conakk, 
Early Akkadian: akk-x-earakk, 
Emesal: sux-x-emesal,
Hittite: hit, 
Late Babylonian: akk-x-ltebab, 
Middle Assyrian: akk-x-midass, 
Middle Babylonian: akk-x-midbab,
Middle Babylonian peripheral: akk-x-mbperi, 
Neo-Assyrian: akk-x-neoass, 
Neo-Babylonian: akk-x-neobab,
Old Akkadian: akk-x-oldakk, 
Old Assyrian: akk-x-oldass, 
Old Babylonian: akk-x-oldbab,
Old Babylonian peripheral: akk-x-obperi, 
Standard Babylonian: akk-x-stdbab, 
Sumerian: sux-x-emegir,
Syllabic: sux-x-syllabic, 
Udgalnun: sux-x-udgalnun, 
Ur III Akkadian: akk-x-ur3akk,
Urartian: xur,
Old Persian: peo,
Hurrian: xhu,
Elamite: elx
```

**Comment by raquel-ucl** [comment]
We can discuss what to do with `Elamite: elx` in the next version. I'll leave it as is for now.

**Comment by niekveldhuis** [comment]
Sounds good to me.
Niek

**Comment by niekveldhuis** [comment]
Btw Luwian is xlu (cuneiform) and hlu (hieroglyphic). I don't know that
anyone is planning to use Luwian, though. The language codes are not ORACC
specific but belong to one of the ISO standards. Usually the Wikipedia
article on a language will give the code.
Niek

**Comment by niekveldhuis** [comment]
I would add uga = ugaritic. This is already used in some ORACC projects.

Niek

Niek Veldhuis
Professor of Assyriology, Department of Near Eastern Studies
Senior Fellow, Berkeley Institute of Data Science
UC Berkeley
