### ISSUE TITLE
Simplify version checking and patching

### ISSUE THREAD

**Issue by ageorgou** [oracc/nammu#403]
At statup, Nammu checks the user's existing settings and compares them to the version in the jar, to determine if any update or patching is needed. This is currently done twice, with no obvious reason for doing so (once in `update_yaml_config`, and then again in `get_yaml_config` directly). It would be nice to clear that up, unless it turns out it's needed (unlikely).

**Comment by giordano** [comment]
For reference, the version checking inside `get_yaml_config` has been introduced in commit https://github.com/oracc/nammu/commit/d422d8ad72b269cff323f41cefd03b4afd3772c6 (PR #293)

**Comment by ageorgou** [comment]
Hm. The version checking was introduced there, but the patching was already present in both places before that. It seems it was introduced in #292 - I wonder who reviewed that 😅

**Comment by giordano** [comment]
Related to this, @ageorgou [suggested](https://github.com/oracc/nammu/pull/406#discussion_r347907720) to close the setting files at some point
