### ISSUE TITLE
Cannot open Nammu on PC

### ISSUE THREAD

**Issue by haider-uoft** [oracc/nammu#419]
Nammu version: 1.3.0
Java version: 1.8.0_291
Platform: Windows 10

When I click on the Nammu icon, the processing wheel flashes momentarily and disappears, and nothing happens. I have set java as the default app to open Nammu, but cannot seem to figure out the issue.

**Comment by raquel-ucl** [comment]
Hi @haider-uoft, thanks for the report. In order for us to understand what the problem could be you'll need to try to open from a terminal. You can open a terminal by going to "Start" and searching for "cmd" or "Command Prompt".
Once the terminal is open, you will need to know where you have saved the Nammu installable file you downloaded. For example, if it is in your Downloads folder, it will be in `C:\Users\%USERNAME%\Downloads`. Then you will have to go to that folder in your terminal like this:

```bash
cd C:\Users\%USERNAME%\Downloads 
```

Then to try to open Nammu and see the error log, you will need to run this:

```bash
java -jar nammu-1.3.0.jar
```

That should now display an error message that'll give us a better idea on what the problem can be.

If there are any problems, please let us know and we can arrange a call.

**Comment by haider-uoft** [comment]
Hello, It worked when I followed the commands you provided in your message. Thank you!

**Comment by raquel-ucl** [comment]
Great! Maybe it now works as well when double clicking on the icon now. The very first time Nammu starts, it sets up some files in you computer to save Nammu's settings and a log file. Maybe this didn't work when you clicked on the icon for some reason (e.g. lack of permissions). Let me know if you need any more help!
