### ISSUE TITLE
Can't open nammu-1.3.0 with Java 17 version, OSX

### ISSUE THREAD

**Issue by wangj619** [oracc/nammu#422]
I got a new Macbook air, so I have to install Nammu again. I download the latest Java version, but couldn't open Nammu.

I wonder, it is because of the java version, or something else?

**Comment by wangj619** [comment]
This is the error report:
![image](https://user-images.githubusercontent.com/37027125/134056881-ac5e047f-1d96-4ba1-83c5-85fdfdf1f6b0.png)

**Comment by ageorgou** [comment]
Hi Jinyan, sorry we haven't been able to look into this yet! Did you solve the issue?

**Comment by wangj619** [comment]
Yes, I resolved it. I found I don’t need jdk 17, so I uninstalled it and downloaded Java 8. Now nammu is working.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ageorgou** [comment]
Great, thank you for the update, and I'm glad it's resolved.

Please note that we are developing a replacement for Nammu, [Nisaba](https://github.com/oracc/nisaba), in part to deal with issues like this. We will be making more information available when it is ready, and will be recommending that people switch to that.
