### ISSUE TITLE
Check ATF files in the ORACC server

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/nammu#60]
- [x] Validate ATF files (this will be done with the parser eventually)
- [x] Lemmatise
- [x] Ask Steve/Eleanor what other actions they want to do in the server.

**Comment by raquel-ucl** [comment]
Validation of ATF is in progress. It doesn't fully work yet. The zip file built on memory to be attached in the request might not be working. The other option is the transfer mechanism is adding bits to the file. It does work for the sample file sent by Steve, but doesn't work for Belsunu, for example. Changing the ordering of the sentences inside the file fixes it sometimes. It is quite unstable at the moment and needs investigating. See #4.

**Comment by raquel-ucl** [comment]
Some more info about the problem I'm having:

Everything goes fine when I try to validate hyphens.atf which has the following content:

```
&P121212=X
#project: tests/mini
#atf: use unicode

#atf: lang xur

1. {lu₂}ha-bi-ru
#lem: +habiru[Habiru]N$
```

If I modify it to make some mistakes:

```
&P121212=X
#project: tests/mini
#atf: use unicode

#atf: lang xur

1. {lu₂}ha-bi-ru
#lem: +habiru[Habiru]N$

1. {lu₂}ha-bi-ru
#lem: +habiru[Habiru]N$

2.  {lu₂}ha-bi-ru {lu₂}ha-bi-ru {lu₂}ha-bi-ru
#lem: +habiru[Habiru]N$
```

I get this from the server:

```
00atf/hyphens.atf:10:P121212: 1: duplicate label (double obv/rev/col/line? One per text reported)
00atf/hyphens.atf:14:P121212: too few lemmata
ATF processor ox issued 3 warnings and 0 notices
```


The problem is when I use other files like belsunu.atf, where I get an empty log from the server about the validation, but I get this in the request.log:

```
warning [/tmp/datay7YGRb]:  6 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  6
  (attempting to re-compensate)
  inflating: 00atf/belsunu.atf
  error:  invalid compressed data to inflate
```

I can trim belsunu.atf until I get a subset of it that works, and then keep on testing adding small bits to it. So this kind of works (notice the lang protocol is uncomplete):

```
&X001001 = JCS 48, 089
#project: cams/gkab
#atf: lang akk-
#atf: use unicode
#atf: use math
@tablet
@obverse
```

However, the server says the zip has one extra byte and seems corrupt (although the server manages to extract it anyway):

```
warning [/tmp/datareNsUS]:  1 extra byte at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  1
  (attempting to re-compensate)
  inflating: 00atf/belsunu.atf
```

If I  change it like this:
```
&X001001 = JCS 48, 089
#project: cams/gkab
#atf: lang akk-x-old
#atf: use unicode
#atf: use math
@tablet
@obverse
```

The server seems to not understand what comes after `#atf: lang akk-`, but manages to extract the file:

```
00atf/belsunu.atf:3:(null): bad UTF-8 character b0
00atf/belsunu.atf:4:(null): bad UTF-8 character b0
00atf/belsunu.atf:5:(null): bad UTF-8 character 84
00atf/belsunu.atf:3:X001001: akk-: bad language tag: expected abc-x-abcdef-1234
00atf/belsunu.atf:5:X001001: : lang is required and must be 2 or 3 letters
```

And this doesn't work at all because the server can't manage to inflate the zip:

```
&X001001 = JCS 48, 089
#project: cams/gkab
#atf: lang akk-x-oldbab
#atf: use unicode
#atf: use math
@tablet
@obverse
```

Things that could be going wrong:

* The python requests library: might be adding extra bytes to the file when sending it.
* The python zipfile module I'm using to create the zip file.
* The server not understanding the zip files I'm sending.
* Hyphens might be causing some confusion somewhere in the code?
* Something else I haven't thought about yet.

I've tried testing the requests module using something like https://httpbin.org or http://requestb.in, but these can't handle multipart SOAP requests. The only way to check I'm sending what I think I'm sending is enabling the server to log the post requests that get to it and comparing with the resquests I send.

I'll keep on looking into this.

**Comment by raquel-ucl** [comment]
I've tried a few more things like making a zip from the command line with both zip and p7zip and with hyphens.atf and belsunu.atf, and sending that to the server. It breaks in all cases. The only case it works well with is the request.zip that Steve sent as an example.

**Comment by jamespjh** [comment]
Interesting...

Can we look at the contents of Steve's zip and see what's different? Maybe check the byte structure of the zip index table?

**Comment by raquel-ucl** [comment]
This last problem creating the zips from the command line was caused by my zips having both the 00atf folder and the atf file inside it compressed, whereas Steve's example was compression only the file. So these two commands produce slightly different zip files:

```
zip -r request.zip 00atf/
```

```
zip request.zip 00atf/hyphens.atf
```

When you open them, they both have a folder with an atf file inside, but inside the file the first one has two compressed items (folder and file) and the second only has one element:

```
zip -sf my_request.zip

Archive contains:
  Users/raquelalegre/Desktop/00atf/
  Users/raquelalegre/Desktop/00atf/hyphens.atf
Total 2 entries (110 bytes)
```

```
zip -sf steves_request.zip

Archive contains:
  00atf/hyphens.atf
Total 1 entries (110 bytes)

```



However we keep on having the original problem where we can't understand why the server can't open some of the zip files we send. 

The server complains about extra bytes in the file, but we've tested the zip files created on our side are valid zip files, and that they are byte by byte exactly the same content as the sample request.zip file sent by Steve (except creation date). We also made sure the requests library sending the HTTP POST request with the binary encoded zip file is correct and hasn't added extra bytes to the file anywhere using [WireShark](https://www.wireshark.org). 

Things could be failing in the way the server is trying to unzip the request.zip sent, or in the way between our client and the server. It would be of help to have an account to log in the server and access to the logs in the server and the bytes of the request.zip we send once it's arrived in the server. This can be done with the xxd command:

```
xxd steves_request.zip

0000000: 504b 0304 1400 0000 0800 a441 7447 2e1a  PK.........AtG..
0000010: d555 6500 0000 6e00 0000 1100 1c00 3030  .Ue...n.......00
0000020: 6174 662f 6879 7068 656e 732e 6174 6655  atf/hyphens.atfU
0000030: 5409 0003 631c 4f56 4a1c 4f56 7578 0b00  T...c.OVJ.OVux..
0000040: 0104 f501 0000 0414 0000 0053 0b30 3402  ...........S.04.
0000050: 41db 082e e582 a2fc acd4 e412 2b85 92d4  A...........+...
0000060: e292 62fd dccc bc4c 2ee5 c492 342b 85d2  ..b....L....4+..
0000070: e254 85d2 bccc e4fc 9454 2ea8 504e 625e  .T.......T..PNb^
0000080: ba42 4569 1117 97a1 9e42 754e e9a3 a6a6  .BEi.....BuN....
0000090: da8c 44dd a44c dda2 522e e59c d45c 2b05  ..D..L..R....\+.
00000a0: ed8c c4a4 cca2 d268 0f30 15eb a7c2 0500  .......h.0......
00000b0: 504b 0102 1e03 1400 0000 0800 a441 7447  PK...........AtG
00000c0: 2e1a d555 6500 0000 6e00 0000 1100 1800  ...Ue...n.......
00000d0: 0000 0000 0100 0000 a081 0000 0000 3030  ..............00
00000e0: 6174 662f 6879 7068 656e 732e 6174 6655  atf/hyphens.atfU
00000f0: 5405 0003 631c 4f56 7578 0b00 0104 f501  T...c.OVux......
0000100: 0000 0414 0000 0050 4b05 0600 0000 0001  .......PK.......
0000110: 0001 0057 0000 00b0 0000 0000 00         ...W.........
``` 

See description of the zip bytes in wikipedia [here](https://en.wikipedia.org/wiki/Zip_(file_format)).

**Comment by raquel-ucl** [comment]
Looking at the problem with Steve and logging in the server revealed the problem was in the way the body was formatted.

The python mime module was creating some new lines with `\r\n` and some with '\n' which confused the server at the beginning, so I was doing this to workaround that problem:

```
body.replace('\r\n\', '\n').replace('\n','\r\n')
```

The body included also the binary encoded attachment, so there were unexpected new lines messing up the bytes in the encoding. I have fixed that now by extracting the encoded text, replacing the `\r\n`s in the rest of the body, then putting the attachment back to the body.

Validating works now!

**Comment by raquel-ucl** [comment]
Code was refactored in #73 to add lemmatisation. However the server is not lemmatising, it returns:

```
xsystem /home/oracc/bin/ox -A -x autolem.atf -l /home/oracc/tmp/sop/wX5DPt/oracc.log -c 00atf/belsunu.atf
ox: emergency stop, program crash. Invoked as:
	/home/oracc/bin/ox -A -x autolem.atf -l /home/oracc/tmp/sop/wX5DPt/oracc.log -c 00atf/belsunu.atf
```

caused by the `ox` command. I've tried copying the file in the server and running the command with different params. `-A` does the lemmatisation. If I remove it, it doesn't break, but only validates and doesn't lemmatise. Steve is looking into this. Otherwise, the functionality in Nammu should be ready.

Errors returned by the validation are processed and lines and highlighted where there are reported errors.

**Comment by raquel-ucl** [comment]
Steve fixed the server last night and now lemmatisation works.

**Comment by raquel-ucl** [comment]
I have noticed a small problem though. I just sent an email to Steve about it:

```
There is one minor thing I'm not sure about. Is it necessary to always validate before 
lemmatising? I say this because for example with belsunu, the validation returns an 
error line (22) and a message, but the autolemmatised file might have a different 
number of lines because things are shifted when adding the lemmas. So line 22 doesn't 
correspond to the errored text anymore. Should I ignore the validation messages that 
come from the lemmatising and only display validation results when the user actively
 clicks on validate? Or should the server do the validation again after the text has been 
lemmatised and return only those validation results?
```

**Comment by raquel-ucl** [comment]
Resolution is that lemmatising only happens if the file is valid. This is how Emacs works at the moment. 

Asked Eleanor about how much priority harvest and other commands have, and seems we are leaving it for next stage after the conference in July.

Lemmatising and validation work, so closing.

**Comment by jamespjh** [comment]
I bet closing that ticket was happy-making.

**Comment by raquel-ucl** [comment]
Yep :)
