### ISSUE TITLE
Show multiple views of text with independent scrolling

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/nammu#63]
From last time we talked, I think Eleanor referred to a split view with independent scrolling.

**Comment by raquel-ucl** [comment]
She wants to be available to write a translation while looking at the lemmatised text.

**Comment by raquel-ucl** [comment]
Work to toggle the split screen done. Now I need to sort out how to synchronise the left and right panels.

I might as well make an option to split horizontal and vertical. I'll ask @EleanorRobson if that's of any use at all, since it'd be quite easy to add both options now.

**Comment by raquel-ucl** [comment]
Synchronisation was easier than I thought since the uneditable panel just needs to point to the editable's StyledDocument. 

Needs some more tests, as focus seems a bit weird sometimes and jumps from fixed place to last edited line.

**Comment by EleanorRobson** [comment]
If it's genuinely easy to have a vertical split, that would be great, as it's good to have both options depending on screen-size, line-length in texts, etc. Thank you!

**Comment by raquel-ucl** [comment]
Done, both options exist now :) I'll show you tomorrow.
