### ISSUE TITLE
Handle server response when there's a server error

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/nammu#88]
Sometimes when I send several hundreds of requests to the server for testing purposes, the server starts returning `err_stat` when waiting for a file validation results. At the moment it just goes on waiting until the status is `Done`, but if the server is down that'll never happen, so it goes on an infinite loop.

**Comment by jamespjh** [comment]
Anything that interacts with a web service should *always* have a timeout, and appropriate exception handling ;-)

**Comment by raquel-ucl** [comment]
Done now :)

**Comment by raquel-ucl** [comment]
More on this: #94
Needs some more work and testing.

**Comment by raquel-ucl** [comment]
Done.
