### ISSUE TITLE
Problems with line endings in windows

### ISSUE THREAD

**Issue by raquel-ucl** [oracc/nammu#99]
When running nammu on Windows, syntax highlight looks wrong if pasting `belsunu.atf` on the text area.
However, opening it from the File->Open menu looks ok.
Also, after clearing the text area, if pasting `belsunu.atf` as in the first step, the syntax highlight works fine.

When the syntax highlight looks wrong seems to be off by one position, which is calculated by the lexer in pyORACC. 

It could also by that the JEditPane is behaving oddly in Windows. 

Needs investigating.

**Comment by jenshnielsen** [comment]
fixed by #102
